import { IExercise } from "../types/IExercise";

export const exercises: IExercise[] = [
  {
    id: "ex-1",
    nodeId: "1",
    problem: "Contains Duplicate",
    link: "https://leetcode.com/problems/contains-duplicate/",
    difficulty: "Easy",
    solution: "https://neetcode.io/solutions/contains-duplicate",
  },
  {
    id: "ex-2",
    nodeId: "1",
    problem: "Valid Anagram",
    link: "https://leetcode.com/problems/valid-anagram/",
    difficulty: "Easy",
    solution: "https://neetcode.io/solutions/valid-anagram",
  },
  {
    id: "ex-3",
    nodeId: "1",
    problem: "Two Sum",
    link: "https://leetcode.com/problems/two-sum/",
    difficulty: "Easy",
    solution: "https://neetcode.io/solutions/two-sum",
  },
  {
    id: "ex-4",
    nodeId: "1",
    problem: "Group Anagrams",
    link: "https://leetcode.com/problems/group-anagrams/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/group-anagrams",
  },
  {
    id: "ex-5",
    nodeId: "1",
    problem: "Top K Frequent Elements",
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/top-k-frequent-elements",
  },
  {
    id: "ex-6",
    nodeId: "1",
    problem: "Encode and Decode Strings",
    link: "https://leetcode.com/problems/encode-and-decode-strings/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/encode-and-decode-strings",
  },
  {
    id: "ex-7",
    nodeId: "1",
    problem: "Product of Array Except Self",
    link: "https://leetcode.com/problems/product-of-array-except-self/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/product-of-array-except-self",
  },
  {
    id: "ex-8",
    nodeId: "1",
    problem: "Valid Sudoku",
    link: "https://leetcode.com/problems/valid-sudoku/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/valid-sudoku",
  },
  {
    id: "ex-9",
    nodeId: "1",
    problem: "Longest Consecutive Sequence",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/longest-consecutive-sequence",
  },
  {
    id: "ex-10",
    nodeId: "2",
    problem: "Valid Palindrome",
    link: "https://leetcode.com/problems/valid-palindrome/",
    difficulty: "Easy",
    solution: "https://neetcode.io/solutions/valid-palindrome",
  },
  {
    id: "ex-11",
    nodeId: "2",
    problem: "Two Sum II Input Array Is Sorted",
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/two-sum-ii-input-array-is-sorted",
  },
  {
    id: "ex-12",
    nodeId: "2",
    problem: "3Sum",
    link: "https://leetcode.com/problems/3sum/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/3sum",
  },
  {
    id: "ex-13",
    nodeId: "2",
    problem: "Container With Most Water",
    link: "https://leetcode.com/problems/container-with-most-water/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/container-with-most-water",
  },
  {
    id: "ex-14",
    nodeId: "2",
    problem: "Trapping Rain Water",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    difficulty: "Hard",
    solution: "https://neetcode.io/solutions/trapping-rain-water",
  },
  {
    id: "ex-15",
    nodeId: "3",
    problem: "Valid Parentheses",
    link: "https://leetcode.com/problems/valid-parentheses/",
    difficulty: "Easy",
    solution: "https://neetcode.io/solutions/valid-parentheses",
  },
  {
    id: "ex-16",
    nodeId: "3",
    problem: "Min Stack",
    link: "https://leetcode.com/problems/min-stack/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/min-stack",
  },
  {
    id: "ex-17",
    nodeId: "3",
    problem: "Evaluate Reverse Polish Notation",
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/evaluate-reverse-polish-notation",
  },
  {
    id: "ex-18",
    nodeId: "3",
    problem: "Generate Parentheses",
    link: "https://leetcode.com/problems/generate-parentheses/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/generate-parentheses",
  },
  {
    id: "ex-19",
    nodeId: "3",
    problem: "Daily Temperatures",
    link: "https://leetcode.com/problems/daily-temperatures/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/daily-temperatures",
  },
  {
    id: "ex-20",
    nodeId: "3",
    problem: "Car Fleet",
    link: "https://leetcode.com/problems/car-fleet/",
    difficulty: "Medium",
    solution: "https://neetcode.io/solutions/car-fleet",
  },
  {
    id: "ex-21",
    nodeId: "3",
    problem: "Largest Rectangle In Histogram",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    difficulty: "Hard",
    solution: "https://neetcode.io/solutions/largest-rectangle-in-histogram",
  },
];
